version: ~> 1.0

language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      services: docker
      compiler: gcc
      env:
        - BUILD_TYPE="docker"
        - DOCKER_IMG="qtio"
    - os: linux
      dist: bionic
      services: docker
      compiler: clang
      env:
        - BUILD_TYPE="docker"
        - DOCKER_IMG="qtio"
    - os: linux
      dist: bionic
      services: docker
      compiler: gcc
      env:
        - BUILD_TYPE="docker"
        - DOCKER_IMG=""
    - os: linux
      dist: bionic
      services: docker
      compiler: gcc
      env:
        - BUILD_TYPE="docker"
        - DOCKER_IMG="eoan"
        - DOCKER_SCRIPT="./tools/build_extra_tests"
    - os: linux
      dist: xenial
      compiler: gcc
      env:
        - BUILD_TYPE="local"
        - QT_VERSION="5.9.9" # 5.12.1 vtesto stmsdf fails with valgrind 3.11.0 which is on xenial
      addons:
        apt:
          packages:
            - expat
            - fop
            - valgrind
            - xsltproc
            - libxml2-utils
            - libusb-1.0-0-dev
            - docbook-xml
            - docbook-xsl
            - libgl1-mesa-dev
            - libxkbcommon-x11-0 # for qt onliner installer 3.2.1
      cache:
        directories:
          - $HOME/Cache
        timeout: 600
    - os: osx
      compiler: clang
      env: QT_VERSION="5.9.9"
      cache:
        directories:
          - $HOME/Cache
        timeout: 600
    - os: osx
      compiler: clang
      env:
      - QT_VERSION="5.12.7"
      - secure: coCEA189fXiCnuAW29OxuLKG24FAVXi3DNg5P8MwuU8Sw5ZsbwYnLoOgOZ08q1FOzjE/lFzVUweGzd48tuWAseyRWD/+8N6BsRGjFwnAysfSFW8tmREYk6qwbs9BzAsbh1YH9NkCBgc+U8z5iRLmrRuAKo88Vfh8e4NiMROP7pESkjmwowkBKzD5wjuzQrTOGTV8kJ2jE9qiPPqgifrjawS7U44QH9k9vV9whlR81UJNIBc4lOFOncnL9+cAaHsF3wpwqFVYT3wtzJgGIB4ERLrUIIwFaOYawgkiITzP7VLqDfIkLty7QpYNASAY0Za4Gm8HLJAFGIG8d7LDXQDXqnejxXY8Vz9WloE4tG08gITaj1rayR+2eyYkCCdVWLN1vH5iUZjgzXAtFN4lxnE92yg+c7xZTLfsNKYNQ+8jJy0Mo7mcJOdXgfW55HkhTy7GaHcj319Yx5/vLuJItsB5NYKBv1mEvjakCKJ9rRXjIu+vPYAkF+ooNkKfBQ1hKQlHUjpY827fwAPqL3NAf4qalQfFcneF/77SztTFYruIJ4n4DwRXpIQJrHnacODhaASP8V1S0uIz1mOXLGo/4c7fT9fzTtnbzX1HOZM7RHVB8wHPCenikMwHKSdH9u2SPlB9uFHhOqtbNGb3YstTEO9NVS0s302B4Jann2YzLN1h//Q=
      - secure: BX1wG9ytNiQUg+98BUatROOFjsjjLBh5VhyQhblGgofrBkufX0bM4ATnO3n9dK1OqycdiRKtzc70X/iTzQfw3GbL+YXP8CIgN1KVNFYKxcWis/tJE9Qub8vN6IYxpuawL403YrNVLmJHOjXWNXcpTOeMGIyLC59tV8XXAwd3TZUYbhEN/61QrqNFvhREsNkuPC03ECb1RilhILs6ZABMA82XRUwNO/vvJ19nnmlKQ/XOrsa9UgrzlrAWdTwxSS7kwhHqdvNgS2rx8SrcPsd7iUqKj+TVOOcQmLFZ12Xs14/716J3HYxUVeRTyixNf9LgLQqNlxz+PYKP68nIX65jDJ5mHZTghJQXY/Hz6zOIfNaGhs9guFvDcbwaVVQ57pU4AOLkTI3iSYG0fFkMpYRqk3DoDnGRKYib4NzccwSxaloEYQPCNC1LZAaQb6cS20rl878cGz1LRkN3kgdbQi5Q8C7CYb89k519vL3pHjJbJwKP7hxOYmJ9cCb/ofNQdR/1Ayw5uuvHWIdlvAamRrgS7ra0QUf+SG8QeEft6d1BItSABHhcvez3DRR5VTPRi1Dieh7hFzDf1ZqJQYvcKrZ3ZtTcnVfwpS6q/99sG583bXFIRqF3UmpQkWxfL152Ni9GiNmzpryPROn5aq5FDBUbW/BBzsefGIx3CvCkScGvPIo=
      - secure: cDDwgn6BloMRRRGDcuXXBnlkdmgT5OvqREjlajQSOdw9tFvUNliLuBwiRMZwm8Ob+rT6f1q/XHLCDtCNnpRQ8jL/v6l7gOkXvT9X4p8WnodlZ+KRPqhkDayKo+hO/VO3QtRozjFU1xAfFq00gprFE+v+gHwKy53YyNubP0ZTNCyal2AJXFqK1r0mHXGQwilDAuY3fSxF7ZXq0dVpI2aT/lqdV4zjX5M+ZkvEvU/WHV3yu0hdtSAYV7hqT/qEjMr7Sogr/X2dAb4sbh++KU31g5Sgs963QL4DKx6q3uIAhlmltZgzbB5GA/55sUgdB+HEZCDegDgfRUNd7v/vg+7YVrPi0/z97UwujHRcsoumJXMa973hJYQnatIpAG/1RvjNHT2Sks88CoNWY5FTaic6yhXNyIyayfOwwe7LLWu8WQFMFvv1p3FanlZcODHJz7R6OuG44/tq1/pY5KARjEyIxj4Cv0fqfWQ+xXJU+cH8hvRb2l22P+d036LTY5MmSBZQ/CIsAxPWFymk3oklUhqnPWhyig08Vq9Ub36y6uyYYM/m0YDA1BWJSlsev+DD5vWeLsZRp8BXRHX+gZvgB2fQnUDt79fGUon2fdr+sQ3+we+F6O+kCORWMKCKPjvAY2iXkKSExBeiyMBXi6dlSrRC4vJv9HV22f6zcW+4lPvyRbw=
      cache:
        directories:
          - $HOME/Cache
        timeout: 600
    - os: linux
      dist: bionic
      compiler: gcc
      env:
        - BUILD_TYPE="coverage"
      addons:
        apt:
          packages:
            - gcovr
            - lcov
            - libusb-1.0-0-dev
            - qt5-default

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ] && [ "${BUILD_TYPE}" = "local" ]; then ./tools/travis_install_linux_local ${QT_VERSION} && source ${HOME}/Cache/qt-${QT_VERSION}.env; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ./tools/travis_install_osx ${QT_VERSION} && source ${HOME}/Cache/qt-${QT_VERSION}.env; fi

script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ] && [ "${BUILD_TYPE}" = "coverage" ]; then ./tools/travis_script_linux_coverage; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ] && [ "${BUILD_TYPE}" = "docker" ]; then ./tools/travis_script_linux_docker ${DOCKER_IMG} ${DOCKER_SCRIPT}; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ] && [ "${BUILD_TYPE}" = "local" ]; then echo $PATH; ./build_and_test; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ./tools/travis_script_osx; fi

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  # only deploy pushes to master or prs that target master.  the prs will go to transfr.sh, the pushes go to github.
  - if [ "${TRAVIS_OS_NAME}" = "osx" ] &&  [ "${QT_VERSION}" = "5.12.7" ] && [ "$TRAVIS_BRANCH" = "master" ]; then bash ./tools/uploadtool/upload.sh  gui/GPSBabel-*.dmg; fi

branches:
  except:
    - /^(?i:continuous)$/  # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous.*windows)$/  # Do not build tags that we create when we upload to GitHub Releases

